version: "3.9"

services:
  pgvector-db:
    image: ankane/pgvector:latest
    container_name: pgvector-db
    environment:
      POSTGRES_PASSWORD: 123456
      POSTGRES_USER: postgres
      POSTGRES_DB: quibli_semantic
    ports:
      - "5433:5432"
    volumes:
      - pgvector_data:/var/lib/postgresql/data

volumes:
  pgvector_data:
